import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { VitePWA } from "vite-plugin-pwa";

const DAY = 24 * 60 * 60;

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: "autoUpdate",
      // Icons in public/ are generated by `npm run icons`
      includeAssets: ["icons/favicon.svg", "icons/apple-touch-icon.png"],
      manifest: {
        id: "/",
        name: "Quran Player",
        short_name: "Quran",
        description:
          "Listen to the Holy Quran with beautiful recitations from renowned reciters.",
        start_url: "/",
        scope: "/",
        display: "standalone",
        background_color: "#000000",
        theme_color: "#0a0a0a",
        categories: ["music", "education", "lifestyle"],
        icons: [
          { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
          { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
          { src: "/icons/maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
        ],
      },
      workbox: {
        // Precache the app shell so it launches instantly from the home screen.
        // Splash screens are only read by iOS at install time, so leave them out.
        globPatterns: ["**/*.{js,css,html,svg,png,webp,woff2}"],
        globIgnores: ["icons/splash-*"],
        navigateFallback: "/index.html",
        runtimeCaching: [
          {
            // Surah list, reciters and per-surah audio URLs. Serve the cached
            // copy straight away and refresh it in the background.
            urlPattern: ({ url }) =>
              url.origin === "https://quranapi.pages.dev" && url.pathname.endsWith(".json"),
            handler: "StaleWhileRevalidate",
            options: {
              cacheName: "quran-api",
              expiration: { maxEntries: 200, maxAgeSeconds: 30 * DAY },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            // Museum cover art never changes for a given URL
            urlPattern: ({ url }) => url.hostname === "images.metmuseum.org",
            handler: "CacheFirst",
            options: {
              cacheName: "artwork",
              expiration: { maxEntries: 60, maxAgeSeconds: 90 * DAY },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          // Recitation audio is deliberately not cached: files are large and
          // streamed with range requests. Offline listening is its own feature.
        ],
      },
    }),
  ],
  server: {
    port: 3000,
  },
});
